chore(release): v3.0.0-beta.14

diff --git a/.github/workflows/release-beta.yml b/.github/workflows/release-beta.yml
--- a/.github/workflows/release-beta.yml
+++ b/.github/workflows/release-beta.yml
@@ -20,23 +20,23 @@ jobs:
           fetch-depth: 0
           ref: ${{ github.event.pull_request.head.sha }}
 
-#      - name: Get commit message
-#        run: |
-#          COMMIT_MESSAGE=$(git log --format=%s -n 1)
-#          FILTERED_MESSAGE="${COMMIT_MESSAGE//[^a-zA-Z0-9.()_:, -]/}"
-#          echo "COMMIT_MESSAGE=${FILTERED_MESSAGE}" >> $GITHUB_ENV
-#      - name: Show commit message
-#        run: echo "$COMMIT_MESSAGE"
-#
-#      - name: Commit message compliance verification
-#        if: |
-#          !startsWith( env.COMMIT_MESSAGE , 'chore(release):' ) ||
-#          !contains( env.COMMIT_MESSAGE , '-beta' )
-#        run: echo "ABORT=true" >> $GITHUB_ENV
-#
-#      - name: Get Tag message
-#        if: contains( env.COMMIT_MESSAGE , '-beta')
-#        run: echo "RELEASE_TAG=beta" >> $GITHUB_ENV
+      - name: Get commit message
+        run: |
+          COMMIT_MESSAGE=$(git log --format=%s -n 1)
+          FILTERED_MESSAGE="${COMMIT_MESSAGE//[^a-zA-Z0-9.()_:, -]/}"
+          echo "COMMIT_MESSAGE=${FILTERED_MESSAGE}" >> $GITHUB_ENV
+      - name: Show commit message
+        run: echo "$COMMIT_MESSAGE"
+
+      - name: Commit message compliance verification
+        if: |
+          !startsWith( env.COMMIT_MESSAGE , 'chore(release):' ) ||
+          !contains( env.COMMIT_MESSAGE , '-beta' )
+        run: echo "ABORT=true" >> $GITHUB_ENV
+
+      - name: Get Tag message
+        if: contains( env.COMMIT_MESSAGE , '-beta')
+        run: echo "RELEASE_TAG=beta" >> $GITHUB_ENV
 #
       - name: Install pnpm
         run: npm i -g pnpm@10
@@ -47,28 +47,30 @@ jobs:
           node-version: '20'
           cache: 'pnpm'
 
-#      - name: Install dependencies
-#        if: env.ABORT != 'true'
-#        run: pnpm install --frozen-lockfile
-#
-#      - name: Run Build
-#        if: env.ABORT != 'true'
-#        run: |
-#          if ! pnpm build; then
-#            echo "构建 nutui-react 失败"
-#            exit 1
-#          fi
-#          if ! pnpm build:taro; then
-#            echo "构建 nutui-react-taro 失败"
-#            exit 1
-#          fi
+      - name: Install dependencies
+        if: env.ABORT != 'true'
+        run: pnpm install --frozen-lockfile
+
+      - name: Run Build
+        if: env.ABORT != 'true'
+        run: |
+          if ! pnpm build; then
+            echo "构建 nutui-react 失败"
+            exit 1
+          fi
+          if ! pnpm build:taro; then
+            echo "构建 nutui-react-taro 失败"
+            exit 1
+          fi
 
       - name: Run Release @nutui/nutui-react
         env:
           NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
-#        run: pnpm --dir ./release/h5 publish:beta
-        run: echo "${{ secrets.NPM_TOKEN }}"
+        if: env.ABORT != 'true'
+        run: pnpm --dir ./release/h5 publish:beta
 
-#      - name: Run Releases @nutui/nutui-react-taro
-#        if: env.ABORT != 'true'
-#        run: pnpm --dir ./release/taro publish:beta
+      - name: Run Releases @nutui/nutui-react-taro
+        env:
+          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
+        if: env.ABORT != 'true'
+        run: pnpm --dir ./release/taro publish:beta
